Update ci and README

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,19 +6,31 @@ on:
       - main
   pull_request:
 
+env:
+  ACTIONS_STEP_DEBUG: true
+
 jobs:
   validate:
     runs-on: ubuntu-latest
     steps:
       - name: Validate
-        run: bash -n status-check.sh
+        run: |
+          if bash -n status-check.sh; then
+            echo "::warning::OK"
+          else
+            echo "::error::ERRO"
+            exit 1
+          fi
 
   test:
     runs-on: ubuntu-latest
     needs: validate
     steps:
-      - name: tests
-        run: echo "Running tests" && exit 0
+      - name: Tests
+        run: |
+          echo "Running tests" 
+          echo "::notice::Tests OK"
+          exit 0
 
   package:
     runs-on: ubuntu-latest
@@ -35,3 +47,12 @@ jobs:
         with:
           name: report
           path: report.zip
+      
+      - name: Summary
+        id: summary
+        run: |
+          echo "### Job Summary" >> $GITHUB_STEP_SUMMARY
+          echo "- OS: \`${{ runner.os }}\`" >> $GITHUB_STEP_SUMMARY
+          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
+          echo "- Result: Tests Ok" >> $GITHUB_STEP_SUMMARY
+          echo "- Artefact: [Download report.zip](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
